### ISSUE TITLE
OSX 10.11.2 El Capitan compile error (cddlib)

### ISSUE THREAD

**Issue by enriquefernandez** [rdeits/iris-distro#34]
IRIS fails to compile in my computer running OSX 10.11.2 El Capitan because cddlib fails to compile.

I get the errors:

```
/bin/sh ../libtool --tag=CC   --mode=link gcc  -g -O2 -L/usr/local/lib  -o fourier_gmp fourier.o ../lib-src-gmp/libcddgmp.la
libtool: link: gcc -g -O2 -o .libs/fourier_gmp fourier.o  -L/usr/local/lib ../lib-src-gmp/.libs/libcddgmp.dylib
Undefined symbols for architecture x86_64:
  "___gmpq_clear", referenced from:
      _main in fourier.o
  "___gmpq_init", referenced from:
      _main in fourier.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [fourier_gmp] Error 1
make: *** [all-recursive] Error 1
```

That originate when trying to compile the folder `src-gmp`.

The problem is that it should be linking gmp, but it doesn't.
That is, from the `src-gmp` folder the make file is trying to do:

```
bin/sh ../libtool --tag=CC   --mode=link gcc  -g -O2 -L/usr/local/lib  -o fourier_gmp fourier.o ../lib-src-gmp/libcddgmp.la
```
which fails. However, adding -lgmp:

```
bin/sh ../libtool --tag=CC   --mode=link gcc  -g -O2 -L/usr/local/lib  -o fourier_gmp fourier.o ../lib-src-gmp/libcddgmp.la -lgmp
```
works fine. This happens for all the .o compontents of `src-gmp`.

Logically this also fails when trying to install Drake WITH_IRIS=ON.

A quick crappy fix consists on changing line 258 of `Makefile` in `cdd_project/src-gmp/Makefile` from:

```
LDADD = ../lib-src-gmp/libcddgmp.la
```

to

```
LDADD = ../lib-src-gmp/libcddgmp.la -lgmp
```

Then Drake builds properly.

The really weird thing is that I'm able to install cddlib using homebrew from source without issues. The formula is [here](https://github.com/Homebrew/homebrew-science/blob/master/cddlib.rb) but it doesn't seem to be doing anything at all about this. The homebrew formula points to an older version of cddlib (0.94g) while IRIS downloads (0.94h). However, I've tried to compile both versions standalone and I get the same errors unless adding the -lgmp flag.

Has anyone else seen this using OSX El Capitan?

Thanks!

**Comment by rdeits** [comment]
I just upgraded to El Capitan this week, and I'm seeing the same issue. That is indeed quite strange. I'll have to add a patch step when building cddlib. 

Thanks for reporting this!

**Comment by enriquefernandez** [comment]
Great, thanks!
I still don't know how Homebrew manages to compile it without seemingly patching the code..
By the way, I warned the author of cddlib, so hopefully he'll fix this on his end.
